### ISSUE TITLE
Failing due to misconfigured max context length

### ISSUE THREAD

**Issue by gramster** [matatonic/openai-url-summary#1]
I am trying to use this with TheBloke's llama2-13B-GPTQ which has a context length of 4096 in its config.json. For some reason this is thinking it is 2048. It may be to do with the openai plugin but I thought opening an issue there could obscure this.

```
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model maximum context length is 2048 tokens. However, your messages resulted in over 2190 tokens.
```

Perhaps I need something in config.yaml but I don't really understand that file. I do have a fully up to date obbagooba install that does mention llama2 in that file.

BTW this is great otherwise; I have been doing summaries with my own scripts using OpenAI but my RTX4090 is idle much of the time so it would be good to use it.

**Comment by matatonic** [comment]
Hi @gramster ! Thanks for the report. This is a pain point with the openai extension. I have some discussion about it here, including a workaround: https://github.com/oobabooga/text-generation-webui/issues/3153 

I am currently away on holidays until the end of Sept, but will be more active again then. Hopefully the workaround (models/config-user.yaml hacks) will work for you until it's fixed.

**Comment by gramster** [comment]
Sadly that hasn't helped. I'm using ExLLama_HF as the loader, set to 4096
tokens. I set the same in config-user.yaml. Still get the same problem.

I also tried going down the opposite route, thinking that I'd rather not
take advantage of the full context length than have it crash. So I set
everything I could to 2048. Still the same.

**Comment by gramster** [comment]
I also tried the Vicuna model you mentioned in the README and had the
same problem. I'll take a deeper look later; this does seem like a bug.

**Comment by gramster** [comment]
Well, duh; I didn't even notice the max_size argument; that seems to solve
the issue.
