### ISSUE TITLE
module 'openai' has no attribute 'OpenAI'

### ISSUE THREAD

**Issue by ufukkosker** [matatonic/openai-url-summary#2]
**Example Url:** 
python summary.py -x -t 'https://www.youtube.com/watch?v=jHoEjvuPoB8'

**Terminal Output:**
```
Traceback (most recent call last):
  File "/Users/tcukosker/Documents/SourceCode/openai-summary/summary.py", line 30, in <module>
    client = openai.OpenAI()
             ^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'OpenAI'
```

**Comment by matatonic** [comment]
This repo needs an update... it's getting pretty out of date. Thanks, I'll take a look asap.

**Comment by matatonic** [comment]
It may just mean you need to `pip install -U openai`

**Comment by matatonic** [comment]
pretty sure that's it, this repo now requires openai>=1.0.0, so you can:
```shell
pip install "openai>=1.0.0"
```

Which should fix this error, but I would recommend
```shell
pip install -U openai
```
For the latest python-openai client.

I will be updating the requirements.txt in the next release.

**Comment by matatonic** [comment]
Updated requirements.txt for openai>=1.0.0.
